In [1]:
#Test for replaybuffer
import torch
import numpy as np
from ReplayBuffer import ReplayBuffer

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
RB = ReplayBuffer(3,device)

In [3]:
obs = np.array([1,2])
action = np.array([0,1,3])
reward =np.array(1)
next_obs = np.array([2,3])
done = np.array(0)

In [4]:
RB.store(obs,action,reward, next_obs, done)
RB.store(obs,action,reward, next_obs, done)
RB.store(obs,action,reward, next_obs, done)
RB.store(obs,action,reward, next_obs, done)

In [5]:
batch = RB.sample(2)
print(batch)

[0 0]
{'observations': array([[1, 2],
       [1, 2]]), 'actions': array([[0, 1, 3],
       [0, 1, 3]]), 'rewards': array([1, 1]), 'next_observations': array([[2, 3],
       [2, 3]]), 'dones': array([0, 0])}


In [6]:
from util import *

In [7]:
num_batch = from_numpy(batch)

In [10]:
print(num_batch)

{'observations': tensor([[1, 2],
        [1, 2]], device='cuda:0'), 'actions': tensor([[0, 1, 3],
        [0, 1, 3]], device='cuda:0'), 'rewards': tensor([1, 1], device='cuda:0'), 'next_observations': tensor([[2, 3],
        [2, 3]], device='cuda:0'), 'dones': tensor([0, 0], device='cuda:0')}


In [19]:
obs = torch.tensor([[3,1,2],[1,2,3]])
actions = torch.tensor([[3,2,5,1,2],[1,2,3,4,5]])

In [20]:
print(obs)

tensor([[3, 1, 2],
        [1, 2, 3]])


In [24]:
x = torch.cat([obs,actions], dim=1)

In [22]:
print(x)

tensor([[3, 1, 2, 3, 2, 5, 1, 2],
        [1, 2, 3, 1, 2, 3, 4, 5]])


In [2]:
from SAC_agent import *
from agent import *

In [1]:
#Test for env.step
import gymnasium as gym
import torch
import numpy as np

env = gym.make("Hopper-v4")
obs , _ = env.reset()
action_dim = env.action_space.shape[0]
obs_dim = env.observation_space.shape[0]

/root/DILLAB/.conda/lib/python3.11/site-packages/gymnasium/envs/registration.py:519: DeprecationWarning: WARN: The environment Hopper-v4 is out of date. You should consider upgrading to version `v5`.
  logger.deprecation(


In [2]:
from SAC_agent import Agent

agent = Agent(obs_dim, action_dim)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
obs = torch.from_numpy(obs)

In [30]:
obs.device

device(type='cuda', index=0)

In [8]:
print(obs.float())

tensor([ 1.2513e+00, -2.8599e-03, -2.4237e-03, -4.2992e-03, -4.2723e-03,
        -1.5862e-03,  1.4625e-03,  5.4137e-04,  2.5411e-03,  4.0714e-04,
        -2.9587e-03])


In [11]:
action = agent.policy.get_action(obs.float())

In [21]:
env.action_space.shape[0]

3

In [ ]:
env.action_space.sample().squeeze()

array([ 0.5587984 , -0.09451637,  0.956371  ], dtype=float32)

In [10]:
print(action)

tensor([-0.7608, -0.5162,  0.7246])


In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [13]:
tt = tt.to(device)

In [14]:
# test for nn.softplus
from agent import Policy
import torch

p = Policy(1,1)

In [16]:
input = torch.tensor([-2.3])

In [17]:
mean ,std = p(input.float())

In [22]:
#Test for Policy
from agent import Policy

p = Policy(3,3)
obs = torch.tensor([1,2,3])
dis = p.squashed_distribution(obs.float())

In [23]:
a = dis.sample()

In [24]:
print(a)

tensor([-0.5117, -0.5481,  0.9691])


In [25]:
print(dis)

Independent(TransformedDistribution(), 1)


In [ ]:
#squeeze
import numpy as np
a = np.array([[1,2,3]])


TypeError: 'tuple' object is not callable

In [16]:
print(a)

[[1 2 3]]


In [18]:
a = a.squeeze(0)

In [19]:
print(a)

[1 2 3]


In [3]:
import torch

In [8]:
A = torch.tensor([1,2,3])

A.dim()

1

In [1]:
import sys

In [2]:
print(sys.path)

['/root/DILLAB/.conda/lib/python311.zip', '/root/DILLAB/.conda/lib/python3.11', '/root/DILLAB/.conda/lib/python3.11/lib-dynload', '', '/root/DILLAB/.conda/lib/python3.11/site-packages']


In [3]:
#Simulation for Expectation, MSE loss
import torch.nn.functional as F

In [6]:
import torch
from torch.distributions import Normal, Independent

# 예시: 3차원 액션 공간
mean = torch.tensor([0.0, 0.0, 0.0])
std = torch.tensor([1.0, 1.0, 1.0])

# 1. 그냥 Normal distribution (다차원이지만 각 차원 독립)
dist_raw = Normal(mean, std)

# 2. Independent wrapper를 씌운 벡터 분포
dist_vec = Independent(dist_raw, reinterpreted_batch_ndims=1)

# 샘플
sample_vec = dist_vec.sample()
sample_raw = dist_raw.sample()
print("샘플:", sample_vec, sample_raw)

# log_prob 계산
log_prob_raw = dist_raw.log_prob(sample_raw)
log_prob_vec = dist_vec.log_prob(sample_vec)

print("\nRaw log_prob (per dimension):", log_prob_raw)
print("Summed log_prob (Independent):", log_prob_vec)

샘플: tensor([-0.9215,  0.5851,  0.2981]) tensor([-0.8884, -0.6725,  0.7429])

Raw log_prob (per dimension): tensor([-1.3136, -1.1451, -1.1949])
Summed log_prob (Independent): tensor(-3.3970)


In [28]:
A=torch.tensor([[1,2,3],[2,3,4]], dtype=torch.float32)
B = torch.tensor([[1,2,3],[2,3,4]], dtype=torch.float32)


print(A.mean(dim=0))
print(A.mean(dim=1))

tensor([1.5000, 2.5000, 3.5000])
tensor([2., 3.])


In [26]:
A.size()

torch.Size([2, 3])

In [34]:
import numpy as np

In [41]:
a= np.array([1])

In [42]:
print(*a.shape)

1


In [ ]:
A = np.empty((15,1))
print(A)

[[6.79905637e-316]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [6.32404027e-322]]


In [46]:
A.shape

(15, 1)

In [48]:
B = A[[1,2,3]]

In [49]:
B

array([[0.],
       [0.],
       [0.]])

In [50]:
A=1
A = np.array(A)

In [51]:
print(A)

1


In [52]:
A.shape

()

In [56]:
s = torch.tensor([[1,2,3],[1,2,3]])

In [58]:
1-s

tensor([[ 0, -1, -2],
        [ 0, -1, -2]])